# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tvl07eMdEnPwzOnIwQYLiFRl5DGedRsL

**Task 07: Querying RDF(s)**
"""

!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "Person" with RDFLib and SPARQL**"""

# TO DO
# RDFLib
ns = Namespace("http://somewhere#")
# Visualize the results
for s, p, o in g.triples((None, RDFS.subClassOf, ns.Person)):
  print(s)

# Sparql
from rdflib.plugins.sparql import prepareQuery

q1 = prepareQuery('''
SELECT ?subject
WHERE {
  ?subject rdfs:subClassOf ns:Person.
}
''',
initNs = {"rdfs":RDFS, "ns":ns}
)
# Visualize the results
for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
# RDFLib
# Visualize the results
for s, p, o in g.triples((None, RDF.type, ns.Person)):
  print(s)

# Sparql
q2 = prepareQuery('''
SELECT ?individual
WHERE {
  ?individual rdf:type ns:Person.
}
''',
initNs = {"rdf":RDF, "ns":ns}
)
# Visualize the results
for r in g.query(q2):
  print(r)

"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**

"""

# TO DO
# RDFLib
# Visualize the results
#todo
for s, p, o in g.triples((None, RDF.type, ns.Person)):
  for n, a, n in g.triples((None, None , RDFS.Class)):
    print(s, a)