# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GHd7FJYgGDTeryDNOcfXKPC3Q_sOrBdg

**Task 07: Querying RDF(s)**
"""

!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "Person" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery
RDFS =  Namespace("https://www.w3.org/2000/01/rdf-schema#")
NS = Namespace("https://somewhere#")
q1 = prepareQuery('''
select ?x where {
?x rdfs:subClassOf ns:Person
}
''',
   initNs = { "rdfs": RDFS, "ns": NS}
   )

for r in g.query(q1):
  print(r.x)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

RDF = Namespace("https://www.w3.org/1999/02/22-rdf-syntax-ns#")
q2 = prepareQuery('''
  SELECT ?x WHERE {
    ?x rdf:type ns:Person.
  }
  ''',
   initNs = { "rdf": RDF, "ns": NS}
)

for r in g.query(q2):
  print(r.x)

"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**

"""

