# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCqEUDehO0OkpwcwtFlloiwT81z3t0ht

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

nsUni = Namespace("http://somewhere#")
g.add((nsUni.University, RDF.type, RDFS.Class))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

tup=(ns.Researcher, RDFS.subClassOf, ns.Person)
g.add(tup)
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

tupJaneSmith=(ns.tupJaneSmith,RDF.type, ns.Researcher)
g.add(tupJaneSmith)
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""

VCARD= Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
tupFullNameJane=(ns.tupJaneSmith,VCARD.FN,Literal("Jane Smith"))
tupG=(ns.JaneSmith,VCARD.GIVEN,Literal("Jane"))
tupFamila=(ns.JaneSmith,VCARD.Family,Literal("Smith"))

g.add(tupJaneSmith)
g.add(tupG)
g.add(tupFamila)
print(g.serialize(format='ttl'))
# Visualize the results

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

tupUpm=(ns.UPM, RDF.type, ns.University)
tupJohn=(ns.JohnSmith,ns.works,ns.UPM)
g.add(tupUpm)
g.add(tupJohn)
# Visualize the results
for s, p, o in g:
  print(s,p,o)